/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.totem.monitoring;

import java.awt.Color;

/**
 *
 * @author Victor
 */
public class Calculator extends javax.swing.JFrame {

    Double totemLinux = 400.00;
    Double totemWindows = 500.00;
    Integer plano = 0;

    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        lbPlano = new javax.swing.JLabel();
        lbLinux = new javax.swing.JLabel();
        lbTotem = new javax.swing.JLabel();
        lbWindows = new javax.swing.JLabel();
        tfTotem = new javax.swing.JTextField();
        tfLinux = new javax.swing.JTextField();
        tfWindows = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        lbResultado = new javax.swing.JLabel();
        cbPlano = new javax.swing.JComboBox<>();
        btnLimpar = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Orçamento");
        setBackground(java.awt.Color.gray);
        setBounds(new java.awt.Rectangle(500, 200, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImages(null);

        lbPlano.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbPlano.setText("Plano:");
        lbPlano.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        lbLinux.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbLinux.setText("-Linux:");
        lbLinux.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        lbTotem.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbTotem.setText("Totens: ");
        lbTotem.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        lbWindows.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbWindows.setText("-Windows:");
        lbWindows.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        tfTotem.setText("0");
        tfTotem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTotemActionPerformed(evt);
            }
        });
        tfTotem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfTotemKeyTyped(evt);
            }
        });

        tfLinux.setText("0");
        tfLinux.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLinuxActionPerformed(evt);
            }
        });
        tfLinux.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfLinuxKeyTyped(evt);
            }
        });

        tfWindows.setText("0");
        tfWindows.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfWindowsActionPerformed(evt);
            }
        });
        tfWindows.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfWindowsKeyTyped(evt);
            }
        });

        btnCalcular.setBackground(new java.awt.Color(51, 255, 255));
        btnCalcular.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        lbResultado.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        lbResultado.setForeground(new java.awt.Color(0, 51, 255));
        lbResultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbResultado.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        cbPlano.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cbPlano.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Básico", "Intermediário", "Premium" }));
        cbPlano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPlanoActionPerformed(evt);
            }
        });

        btnLimpar.setBackground(new java.awt.Color(51, 255, 255));
        btnLimpar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbTotem)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfTotem, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(lbLinux))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(67, 67, 67)
                                        .addComponent(cbPlano, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbWindows)
                                        .addGap(18, 18, 18)
                                        .addComponent(tfWindows, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(tfLinux, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbPlano)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33)
                                        .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 103, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTotem, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTotem, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfLinux, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbLinux, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbWindows, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfWindows, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbPlano, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(cbPlano))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(lbResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleName("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfLinuxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfLinuxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfLinuxActionPerformed

    private void tfWindowsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfWindowsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfWindowsActionPerformed

    private void cbPlanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPlanoActionPerformed
        plano = cbPlano.getSelectedIndex();
    }//GEN-LAST:event_cbPlanoActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        int totem, linux, windows;
        totem = Integer.valueOf(tfTotem.getText());
        linux = Integer.valueOf(tfLinux.getText());
        windows = Integer.valueOf(tfWindows.getText());

        if ((windows + linux) != totem) {
            lbResultado.setForeground(Color.red);
            lbResultado.setText("Por favor, coloque a quantidade sistemas"
                    + " operacionais equivalente aos Totens");
        }
        else if (totem == 0) {
            lbResultado.setForeground(Color.red);
            lbResultado.setText("Por favor, insira pelo menos 1 totem");
        }
        else {
            double precoPlano;
            switch (plano) {
                case 0:
                    precoPlano = 100.00;
                    break;
                case 1:
                    precoPlano = 200.00;
                    break;
                default:
                    precoPlano = 300.00;
                    break;
            }
            Double res = (totemLinux * linux) + (totemWindows * windows)
                    + precoPlano;
            lbResultado.setText("Seu custo mensal para contratar nossos serviços "
                    + "será de R$" + res);

        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        tfLinux.setText("0");
        tfTotem.setText("0");
        tfWindows.setText("0");
        lbResultado.setText("");
        cbPlano.setSelectedIndex(0);
    }//GEN-LAST:event_btnLimparActionPerformed

    private void tfTotemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTotemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTotemActionPerformed

    private void tfTotemKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfTotemKeyTyped
        String caracteres = "0987654321";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_tfTotemKeyTyped

    private void tfLinuxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfLinuxKeyTyped
        String caracteres = "0987654321";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_tfLinuxKeyTyped

    private void tfWindowsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfWindowsKeyTyped
        String caracteres = "0987654321";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_tfWindowsKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JComboBox<String> cbPlano;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lbLinux;
    private javax.swing.JLabel lbPlano;
    private javax.swing.JLabel lbResultado;
    private javax.swing.JLabel lbTotem;
    private javax.swing.JLabel lbWindows;
    private javax.swing.JTextField tfLinux;
    private javax.swing.JTextField tfTotem;
    private javax.swing.JTextField tfWindows;
    // End of variables declaration//GEN-END:variables
}
